<!doctype html>
<html lang="{{ app()->getLocale() }}" dir="{{ app()->getLocale() === 'ar' ? 'rtl' : 'ltr' }}">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{{ __('crm.my_call_profile') }} - SokratCRM</title>
<link rel="icon" type="image/png" href="{{ asset('favicon.png') }}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
<link rel="stylesheet" href="{{ asset('css/tajawal.css') }}?v=1.0.0">
<link rel="stylesheet" href="{{ asset('crm-sidebar-shared.css') }}?v=crm-theme-matrix-v4">
<style>
:root{--red:#dc2637;--ink:#172033;--muted:#64748b;--line:#e2e8f0;--bg:#f5f7fa;--card:#fff;--green:#15803d;--blue:#0369a1}
*{box-sizing:border-box}body{margin:0;min-width:320px;background:var(--bg);color:var(--ink);font-family:var(--font-primary)}.app{display:flex;min-height:100vh}.main{flex:1;min-width:0;padding:26px 32px 60px}.top{display:flex;justify-content:space-between;align-items:center;gap:18px;margin-bottom:22px}.top h1{margin:0;font-size:27px}.top p{margin:5px 0 0;color:var(--muted)}.identity{display:flex;align-items:center;gap:13px}.avatar{width:50px;height:50px;border-radius:15px;display:grid;place-items:center;background:#fff0f1;color:var(--red);font-size:21px;font-weight:900}.panel{background:var(--card);border-radius:16px;padding:22px;margin-bottom:20px;box-shadow:0 12px 34px rgba(15,23,42,.06)}.filter{display:grid;grid-template-columns:repeat(4,minmax(0,1fr)) auto;gap:12px;align-items:end}.filter label{display:block;font-size:12px;font-weight:800;color:var(--muted);margin-bottom:6px}.filter input,.filter select{width:100%;border:1px solid var(--line);border-radius:10px;padding:10px;background:var(--card);font:inherit}.btn{display:inline-flex;align-items:center;justify-content:center;gap:6px;min-height:40px;padding:0 14px;border:1px solid var(--line);border-radius:10px;background:#fff;color:var(--ink);font-weight:800;text-decoration:none;cursor:pointer}.btn.primary{background:var(--red);border-color:var(--red);color:#fff}.metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.metric{padding:18px;background:var(--bg);border-radius:14px}.metric span{display:block;font-size:12px;color:var(--muted);font-weight:800}.metric strong{display:block;font-size:27px;margin-top:7px;font-variant-numeric:tabular-nums}.visuals{display:grid;grid-template-columns:1fr 1fr;gap:18px}.visual h2{margin:0 0 16px;font-size:16px}.bar-row{display:grid;grid-template-columns:100px 1fr 38px;gap:10px;align-items:center;margin-top:12px;font-size:12px;font-weight:800}.track{height:9px;background:var(--line);border-radius:999px;overflow:hidden}.fill{display:block;height:100%;border-radius:inherit}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;min-width:850px}th,td{text-align:start;padding:12px 10px;border-bottom:1px solid #edf0f4}th{font-size:12px;color:var(--muted);background:#fafbfc}.badge{display:inline-flex;padding:5px 9px;border-radius:999px;background:#eef2f7;font-size:12px;font-weight:800}.empty{text-align:center;padding:42px 20px;color:var(--muted)}audio{width:190px;height:32px}@media(max-width:1000px){.filter{grid-template-columns:1fr 1fr}.metrics{grid-template-columns:1fr 1fr}}@media(max-width:720px){.main{padding:18px 14px}.top{align-items:flex-start;flex-direction:column}.filter,.metrics,.visuals{grid-template-columns:1fr}.panel{padding:17px}}
</style>
</head>
<body>
<!-- THESIS: Employee call work is a traceable operating record, not a generic account dashboard. OWN-WORLD: SokratCRM's restrained white workspace, compact red controls, and dense tabular evidence. STORY: identify the employee, constrain the period, understand call outcomes, then inspect or replay evidence. FIRST VIEWPORT: identity and extension lead into filters and four operating measures. FORM: established-world extension, profile call ledger. FINISH: unreviewed and undocumented is unfinished; this build ends with the finish review, the verdict, DESIGN.md, and every shipping raster carrying its provenance. -->
@include('partials.page-loader')
<div class="app">@include('partials.crm-sidebar')<main class="main">
<header class="top"><div class="identity"><span class="avatar">{{ mb_substr($user->name, 0, 1) }}</span><div><h1>{{ __('crm.my_call_profile') }}</h1><p>{{ $user->name }} · {{ __('crm.extension_short') }} {{ $user->voip_extension ?: __('crm.none') }}</p></div></div>@include('partials.profile-dropdown')</header>

<section class="panel"><form class="filter" method="GET" action="{{ route('v2.voip.profile') }}">
<div><label for="fromDate">{{ __('crm.from_date') }}</label><input id="fromDate" name="from_date" type="date" value="{{ $filters['from_date'] ?? '' }}"></div>
<div><label for="toDate">{{ __('crm.to_date') }}</label><input id="toDate" name="to_date" type="date" value="{{ $filters['to_date'] ?? '' }}"></div>
<div><label for="direction">{{ __('crm.direction') }}</label><select id="direction" name="direction"><option value="">{{ __('crm.all_directions') }}</option><option value="incoming" @selected(($filters['direction'] ?? '') === 'incoming')>{{ __('crm.incoming') }}</option><option value="outgoing" @selected(($filters['direction'] ?? '') === 'outgoing')>{{ __('crm.outgoing') }}</option><option value="internal" @selected(($filters['direction'] ?? '') === 'internal')>{{ __('crm.internal') }}</option></select></div>
<div><label for="status">{{ __('crm.call_status') }}</label><select id="status" name="status"><option value="">{{ __('crm.all_call_statuses') }}</option>@foreach (['answered','missed','failed','busy','no_answer'] as $status)<option value="{{ $status }}" @selected(($filters['status'] ?? '') === $status)>{{ __('crm.status_'.$status) }}</option>@endforeach</select></div>
<button class="btn primary" type="submit"><i class="bi bi-funnel"></i>{{ __('crm.apply_filters') }}</button>
</form></section>

@if($error)<div class="panel" style="color:#b42332">{{ __('crm.pbx_server_error') }} {{ $error }}</div>@endif
@if(!$user->voip_extension)<section class="panel empty"><i class="bi bi-telephone-x" style="font-size:30px"></i><p>{{ __('crm.profile_needs_extension') }}</p></section>
@elseif($insights)
@php $s=$insights['summary'];$directions=$insights['charts']['directions'];$maxDirection=max(1,...array_values($directions));$dispositions=$insights['charts']['dispositions'];$maxDisposition=max(1,...array_values($dispositions ?: [1])); @endphp
<section class="metrics" style="margin-bottom:20px"><div class="metric"><span>{{ __('crm.total_calls') }}</span><strong>{{ number_format($s['total_calls']) }}</strong></div><div class="metric"><span>{{ __('crm.answer_rate') }}</span><strong>{{ number_format($s['answer_rate_percent'],1) }}%</strong></div><div class="metric"><span>{{ __('crm.total_talk_time') }}</span><strong>{{ floor($s['total_talk_seconds']/60) }}:{{ str_pad((string)($s['total_talk_seconds']%60),2,'0',STR_PAD_LEFT) }}</strong></div><div class="metric"><span>{{ __('crm.missed_calls') }}</span><strong>{{ number_format($s['missed_calls']) }}</strong></div></section>
<section class="visuals"><div class="panel visual"><h2>{{ __('crm.call_direction_mix') }}</h2>@foreach(['outbound'=>[__('crm.outgoing'),'#0284c7'],'inbound'=>[__('crm.incoming'),'#16a34a'],'internal'=>[__('crm.internal'),'#64748b']] as $key=>$meta)<div class="bar-row"><span>{{ $meta[0] }}</span><span class="track"><span class="fill" style="width:{{ (($directions[$key]??0)/$maxDirection)*100 }}%;background:{{ $meta[1] }}"></span></span><b>{{ $directions[$key]??0 }}</b></div>@endforeach</div><div class="panel visual"><h2>{{ __('crm.call_outcomes') }}</h2>@forelse($dispositions as $key=>$count)<div class="bar-row"><span>{{ __('crm.status_'.$key) }}</span><span class="track"><span class="fill" style="width:{{ ($count/$maxDisposition)*100 }}%;background:{{ $key==='answered'?'#16a34a':'#dc2637' }}"></span></span><b>{{ $count }}</b></div>@empty<div class="empty">{{ __('crm.no_calls_match_filters') }}</div>@endforelse</div></section>
<section class="panel"><h2 style="margin:0 0 16px;font-size:17px">{{ __('crm.latest_inbound_outbound_calls') }}</h2><div class="table-wrap"><table><thead><tr><th>{{ __('crm.datetime') }}</th><th>{{ __('crm.direction') }}</th><th>{{ __('crm.other_party') }}</th><th>{{ __('crm.duration') }}</th><th>{{ __('crm.call_status') }}</th><th>{{ __('crm.call_recording') }}</th></tr></thead><tbody>@forelse($insights['calls'] as $call)<tr><td dir="ltr">{{ $call['call_date'] }}</td><td><span class="badge">{{ __('crm.'.($call['direction']==='inbound'?'incoming':($call['direction']==='outbound'?'outgoing':'internal'))) }}</span></td><td dir="ltr">{{ $call['customer_number']??'—' }}</td><td>{{ $call['duration_formatted'] }}</td><td>{{ __('crm.status_'.$call['disposition']) }}</td><td>@if($call['recording_url'])<audio controls preload="none" src="{{ $call['recording_url'] }}"></audio>@else — @endif</td></tr>@empty<tr><td colspan="6" class="empty">{{ __('crm.no_calls_match_filters') }}</td></tr>@endforelse</tbody></table></div></section>
@elseif(!$error)
<section class="panel empty">{{ __('crm.no_extension_statistics') }}</section>
@endif
</main></div><script src="{{ asset('crm-sidebar.js') }}"></script>
</body></html>
