<?php

declare(strict_types=1);

namespace Tests\Feature;

use App\Models\Group;
use App\Models\Permission;
use App\Models\User;
use App\Security\CrmPermission;
use Database\Seeders\CrmAccessControlSeeder;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Support\Facades\Hash;
use Tests\TestCase;

class AuthenticationTest extends TestCase
{
    use DatabaseTransactions;

    public function test_installer_user_is_seeded_as_the_default_super_admin(): void
    {
        config()->set('crm.bootstrap_admin', [
            'name' => 'Current CRM Admin',
            'username' => 'admin',
            'email' => 'admin@example.test',
            'password' => 'Admin@123',
        ]);

        $this->seed(CrmAccessControlSeeder::class);

        $admin = User::query()
            ->where('username', 'admin')
            ->firstOrFail();

        $this->assertTrue($admin->is_active);
        $this->assertTrue(Hash::check('Admin@123', $admin->password));
        $this->assertTrue($admin->isSuperAdmin());
        $this->assertTrue(
            $admin->hasPermission(CrmPermission::GROUPS_ASSIGN_PERMISSIONS),
        );
        $this->assertSame(
            count(CrmPermission::cases()) + Group::query()->count(),
            Permission::query()->count(),
        );
    }

    public function test_active_database_user_can_log_in_and_log_out(): void
    {
        $user = User::factory()->create([
            'username' => 'sales-agent',
            'password' => 'SecretPass123',
            'is_active' => true,
            'last_login_at' => null,
        ]);

        $response = $this->post('/login', [
            'username' => 'sales-agent',
            'password' => 'SecretPass123',
        ]);

        $response->assertRedirect(route('dashboard'));
        $this->assertAuthenticatedAs($user);
        $this->assertNotNull($user->fresh()->last_login_at);

        $this->post('/logout')->assertRedirect(route('login'));
        $this->assertGuest();
    }
    public function test_user_can_log_in_with_display_name_or_email(): void
    {
        $user = User::factory()->create([
            'name' => 'أحمد علي محمد',
            'username' => 'ahmed_ali_101',
            'email' => 'ahmed.ali@example.com',
            'password' => 'SecretPass123',
            'is_active' => true,
        ]);

        // 1. Log in with full display name (Arabic)
        $responseName = $this->post('/login', [
            'username' => 'أحمد علي محمد',
            'password' => 'SecretPass123',
        ]);
        $responseName->assertRedirect(route('dashboard'));
        $this->assertAuthenticatedAs($user);
        $this->post('/logout');

        // 2. Log in with email
        $responseEmail = $this->post('/login', [
            'username' => 'ahmed.ali@example.com',
            'password' => 'SecretPass123',
        ]);
        $responseEmail->assertRedirect(route('dashboard'));
        $this->assertAuthenticatedAs($user);
    }

    public function test_user_can_be_created_with_just_name_and_username_is_autogenerated(): void
    {
        $admin = User::factory()->create(['username' => 'admin_super_user', 'is_active' => true]);
        $superGroup = Group::query()->firstOrCreate(['code' => Group::SUPER_ADMIN_CODE], ['name' => 'Super Admin', 'is_system' => true]);
        $permSettings = Permission::query()->firstOrCreate(['code' => CrmPermission::SETTINGS_ACCESS->value], ['name_ar' => 'الإعدادات', 'module' => 'settings']);
        $permCreate = Permission::query()->firstOrCreate(['code' => CrmPermission::USERS_CREATE->value], ['name_ar' => 'إنشاء مستخدم', 'module' => 'users']);
        $superGroup->permissions()->syncWithoutDetaching([$permSettings->id, $permCreate->id]);
        $admin->groups()->sync([$superGroup->id]);
        $targetGroup = Group::query()->firstOrCreate(['code' => 'staff_grp'], ['name' => 'Staff Grp', 'is_system' => false]);
        $response = $this->actingAs($admin)->post(route('v2.settings.users.store'), [
            'name' => 'محمود مصطفى كمال',
            'password' => 'SecretPassword123!',
            'password_confirmation' => 'SecretPassword123!',
            'group_ids' => [$targetGroup->id],
        ]);

        $response->assertSessionHasNoErrors();
        $newUser = User::query()->where('name', 'محمود مصطفى كمال')->firstOrFail();
        $this->assertNotEmpty($newUser->username);
        $this->assertMatchesRegularExpression('/^[a-z0-9_]+$/i', $newUser->username);
    }

    public function test_inactive_user_cannot_log_in(): void
    {
        User::factory()->create([
            'username' => 'disabled-user',
            'password' => 'SecretPass123',
            'is_active' => false,
        ]);

        $this->post('/login', [
            'username' => 'disabled-user',
            'password' => 'SecretPass123',
        ])->assertSessionHasErrors('login');

        $this->assertGuest();
    }

    public function test_deactivated_user_with_an_existing_session_is_logged_out(): void
    {
        $user = User::factory()->create([
            'is_active' => false,
        ]);

        $this->actingAs($user)
            ->get('/settings')
            ->assertRedirect(route('login'));

        $this->assertGuest();
    }

    public function test_protected_crm_routes_require_authentication(): void
    {
        $this->get('/dashboard')->assertRedirect(route('login'));
        $this->get('/settings')->assertRedirect(route('login'));
        $this->get('/campaigns')->assertRedirect(route('login'));
    }
}
