<?php

declare(strict_types=1);

namespace Tests\Feature\Authorization;

use App\Models\Group;
use App\Models\Permission;
use App\Models\User;
use App\Security\CrmPermission;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Tests\TestCase;

class GroupManagementTest extends TestCase
{
    use DatabaseTransactions;

    private User $superAdmin;

    protected function setUp(): void
    {
        parent::setUp();

        $this->superAdmin = User::factory()->create(['username' => 'group_mgr_admin', 'is_active' => true]);
        $superGroup = Group::query()->firstOrCreate(['code' => Group::SUPER_ADMIN_CODE], ['name' => 'Super Admin', 'is_system' => true]);
        $permSettings = Permission::query()->firstOrCreate(['code' => CrmPermission::SETTINGS_ACCESS->value], ['name_ar' => 'الإعدادات', 'module' => 'settings']);
        $permGroupCreate = Permission::query()->firstOrCreate(['code' => CrmPermission::GROUPS_CREATE->value], ['name_ar' => 'إنشاء مجموعات', 'module' => 'groups']);
        $permGroupUpdate = Permission::query()->firstOrCreate(['code' => CrmPermission::GROUPS_UPDATE->value], ['name_ar' => 'تعديل مجموعات', 'module' => 'groups']);

        $superGroup->permissions()->syncWithoutDetaching([$permSettings->id, $permGroupCreate->id, $permGroupUpdate->id]);
        $this->superAdmin->groups()->sync([$superGroup->id]);
    }

    public function test_group_create_view_renders_code_as_automatic_preview(): void
    {
        $response = $this->actingAs($this->superAdmin)->get(route('v2.settings.groups.create'));

        $response->assertOk();
        $response->assertSee('معاينة تلقائية');
        $response->assertSee('group_code_preview_text');
        $response->assertDontSee('name="code"', false);
    }

    public function test_group_can_be_created_without_code_and_code_is_autogenerated(): void
    {
        $response = $this->actingAs($this->superAdmin)->post(route('v2.settings.groups.store'), [
            'name' => 'مسؤولو التحصيل الميداني',
            'description' => 'إشراف ومتابعة المحصلين',
        ]);

        $response->assertRedirect();

        $group = Group::query()->where('name', 'مسؤولو التحصيل الميداني')->firstOrFail();
        $this->assertNotEmpty($group->code);
        $this->assertMatchesRegularExpression('/\A[a-z0-9]+(?:-[a-z0-9]+)*\z/', $group->code);
        $this->assertFalse($group->is_system);
    }

    public function test_group_autogenerated_code_handles_english_and_collisions(): void
    {
        $res1 = $this->actingAs($this->superAdmin)->post(route('v2.settings.groups.store'), [
            'name' => 'VIP Donors Care',
        ]);
        $res1->assertRedirect();
        $g1 = Group::query()->where('name', 'VIP Donors Care')->firstOrFail();
        $this->assertSame('vip-donors-care', $g1->code);

        // Collision with exact same name
        $res2 = $this->actingAs($this->superAdmin)->post(route('v2.settings.groups.store'), [
            'name' => 'VIP Donors Care',
        ]);
        $res2->assertRedirect();
        $g2 = Group::query()->where('id', '!=', $g1->id)->where('name', 'VIP Donors Care')->firstOrFail();
        $this->assertSame('vip-donors-care-2', $g2->code);
    }

    public function test_group_update_preserves_code_without_requiring_it_in_submission(): void
    {
        $group = Group::query()->create([
            'name' => 'فريق المتابعة القديم',
            'code' => 'followup-team-alpha',
            'is_system' => false,
        ]);

        $response = $this->actingAs($this->superAdmin)->patch(route('v2.settings.groups.update', $group), [
            'name' => 'فريق المتابعة المحدث',
            'description' => 'وصف محدث',
        ]);

        $response->assertRedirect();

        $group->refresh();
        $this->assertSame('فريق المتابعة المحدث', $group->name);
        $this->assertSame('followup-team-alpha', $group->code);
    }

    public function test_system_collection_manager_group_has_all_17_permissions(): void
    {
        $group = Group::query()->where('code', Group::COLLECTION_MANAGER_CODE)->firstOrFail();

        $this->assertTrue($group->is_system);
        $this->assertTrue($group->isCollectionManager());
        $this->assertTrue(in_array(Group::COLLECTION_MANAGER_CODE, Group::SYSTEM_CODES, true));

        $expectedPerms = [
            // Part 1: Core Collection
            'collections.view',
            'collections.assign',
            'collections.manage',
            'collections.cancel',
            'collections.reports',
            // Part 2: Dashboard & Reports
            'dashboard.view',
            'reports.view',
            'reports.employees.view',
            // Part 3: Donors, Follow-ups, Tasks & Calendar
            'leads.view',
            'leads.scope.group',
            'leads.followups.view',
            'tasks.view',
            'calendar.view',
            'calendar.manage',
            // Part 4: Advanced & Configuration
            'collections.methods.manage',
            'collections.geography.manage',
            'collections.escalations.respond',
        ];

        $groupPermCodes = $group->permissions()->pluck('code')->all();
        foreach ($expectedPerms as $perm) {
            $this->assertContains($perm, $groupPermCodes, "Group is missing permission: {$perm}");
        }
    }
}
